#!/usr/bin/python
"""framefan - cap the Steam Frame's fan below Valve's stock top speed.

The Frame's fan (hwmon `slg4ax46073v`, pwm1 = duty cycle 0-100%) is driven by Valve's
deckard-fan-control service, which never goes above `fan_max_speed` (55% stock).
Rather than fight that service, `run` starts Valve's own controller with a lower
fan_max_speed, so their temperature curve stays in charge and only the ceiling moves.
Anything unexpected (e.g. an OS update changed their code) falls back to running the
stock controller untouched.

The cap lives in /etc/framefan/cap (a percentage, owned by the steamos user so the VR
panel can change it). The running controller re-reads it every second; values outside
55-100 are ignored.

The kernel's CPU/GPU throttling is separate from the fan and is not affected: with a
lower fan cap, a hot headset throttles sooner instead of blowing harder.

  framefan.py status          fan duty, RPM, active cap, hottest sensor
  framefan.py check 85        dry run: build the capped controller without starting it
  framefan.py run [85]        what the service runs (cap file wins over the argument)
  framefan.py stop            what the service runs on stop: park the fan at the cap

PERCENT is a share of Valve's stock top speed: 100 = stock, 85 = 85% of it.
"""
import argparse
import glob
import os
import sys
import tempfile

VALVE_DIR = "/usr/share/deckard-fan-control"
VALVE_SCRIPT = VALVE_DIR + "/fancontrol.py"
VALVE_CONFIG = VALVE_DIR + "/deckard-config.yaml"
CAP_FILE = "/etc/framefan/cap"
RUN_DIR = "/run/framefan"
FAN_NAME = "slg4ax46073v"
RPM_SCALE = 2  # the fan's tach reports 2 periods per revolution
STOCK_MAX, IDLE = 55, 30  # Valve's values today; the live ones come from their config
MIN_PCT = -(-IDLE * 100 // STOCK_MAX)  # 55: lower would put the cap under idle speed


def read(p):
    try:
        with open(p) as f:
            return f.read().strip()
    except OSError:
        return None


def fan_dir():
    for h in glob.glob("/sys/class/hwmon/hwmon*"):
        if read(h + "/name") == FAN_NAME:
            return h
    sys.exit(f"no {FAN_NAME} fan found")


def read_cap_file():
    """The configured percentage, or None if missing or out of range."""
    try:
        pct = float(read(CAP_FILE))
    except (TypeError, ValueError):
        return None
    return pct if MIN_PCT <= pct <= 100 else None


def load_valve_config():
    import yaml
    with open(VALVE_CONFIG) as f:
        return yaml.safe_load(f)


def cap_duty(cfg, percent):
    """Duty cycle for PERCENT of stock, rounded down. Refuses to go below Valve's idle speed."""
    stock, floor = cfg["fan_max_speed"], cfg["fan_min_speed"]
    duty = int(stock * percent / 100)
    if duty < floor:
        raise ValueError(f"{percent:g}% of stock is {duty}% duty, below the fan's idle speed of "
                         f"{floor}%; lowest allowed is {-(-floor * 100 // stock)}")
    return min(duty, stock)


def capped_config(cfg, duty):
    cfg = dict(cfg)
    cfg["fan_max_speed"] = duty
    # The charging minimum (40% stock) must not sit above the cap.
    cfg["fan_charging_min_speed"] = min(cfg["fan_charging_min_speed"], duty)
    return cfg


def write_config(cfg):
    import yaml
    try:
        os.makedirs(RUN_DIR, exist_ok=True)
        path = RUN_DIR + "/deckard-config.yaml"
        open(path, "w").close()
    except OSError:  # not root (check): use a throwaway file
        path = tempfile.mkstemp(suffix=".yaml")[1]
    with open(path, "w") as f:
        f.write(f"# generated by framefan from {VALVE_CONFIG}\n")
        yaml.safe_dump(cfg, f, sort_keys=False)
    return path


def build_controller(percent):
    cfg = load_valve_config()
    duty = cap_duty(cfg, percent)
    path = write_config(capped_config(cfg, duty))
    sys.path.insert(0, VALVE_DIR)
    import fancontrol
    return fancontrol.FanController(config_file=path), cfg, duty


def follow_cap_file(controller, cfg, duty):
    """Re-read CAP_FILE before every fan write and move the ceiling live."""
    fan = controller.fan
    seen = {"mtime": None, "duty": duty}
    set_speed, apply_hysteresis = fan.set_speed, fan._apply_hysteresis

    def checked_set_speed(speed):
        try:
            mtime = os.stat(CAP_FILE).st_mtime_ns
        except OSError:
            mtime = None
        if mtime != seen["mtime"]:
            seen["mtime"] = mtime
            pct = read_cap_file()
            if pct is not None and (new := cap_duty(cfg, pct)) != seen["duty"]:
                seen["duty"] = new
                fan.max_speed = new
                fan.charge_min_speed = min(cfg["fan_charging_min_speed"], new)
                for device in controller.devices:
                    device.fan_max_speed = new
                fan._reset_hysteresis()
                print(f"framefan: cap now {pct:g}% of stock = {new}% duty", flush=True)
        set_speed(speed)

    fan.set_speed = checked_set_speed
    # Valve's hysteresis can hold an older, higher speed; never let it outrank the cap.
    fan._apply_hysteresis = lambda speed: min(apply_hysteresis(speed), fan.max_speed)


# ---- commands ----

def cmd_status(args):
    h = fan_dir()
    duty, rpm = read(h + "/pwm1"), read(h + "/fan1_input")
    print(f"fan: {duty}% duty, {int(rpm) // RPM_SCALE if rpm else '?'} rpm")
    pct = read_cap_file()
    if os.path.exists(RUN_DIR + "/deckard-config.yaml") and pct is not None:
        print(f"cap: {pct:g}% of stock = {int(STOCK_MAX * pct / 100)}% duty (framefan active)")
    else:
        print(f"cap: none (stock {STOCK_MAX}% duty)")
    temps = []
    for z in glob.glob("/sys/class/thermal/thermal_zone*"):
        t = read(z + "/temp")
        if t and t.lstrip("-").isdigit():
            temps.append((int(t) / 1000, read(z + "/type")))
    if temps:
        t, name = max(temps)
        print(f"hottest: {name} {t:.1f} C")


def cmd_check(args):
    try:
        controller, cfg, duty = build_controller(args.percent)
    except ValueError as e:
        sys.exit(str(e))
    devs = {d.fan_max_speed for d in controller.devices}
    print(f"stock top speed {cfg['fan_max_speed']}% duty -> capped at {duty}% duty (~{duty * 100} rpm)")
    print(f"controller fan max: {controller.fan.max_speed}, overheat fallback: {sorted(devs)}, "
          f"charging min: {controller.fan.charge_min_speed}, idle min: {controller.fan.min_speed}")


def cmd_run(args):
    pct = read_cap_file() or args.percent or 100
    try:
        controller, cfg, duty = build_controller(pct)
        follow_cap_file(controller, cfg, duty)
    except BaseException as e:
        print(f"framefan: cannot apply cap ({e!r}); running Valve's controller unmodified", flush=True)
        if os.path.exists(RUN_DIR + "/deckard-config.yaml"):
            os.remove(RUN_DIR + "/deckard-config.yaml")
        os.execv(VALVE_SCRIPT, [VALVE_SCRIPT, "--run"])
    print(f"framefan: fan capped at {pct:g}% of stock = {duty}% duty (stock {cfg['fan_max_speed']}%)",
          flush=True)
    controller.loop_control()
    controller.on_exit(None, None)


def cmd_stop(args):
    # Valve parks the fan at its top speed when the controller stops; park it at the cap instead.
    try:
        duty = cap_duty(load_valve_config(), read_cap_file() or 100)
    except BaseException:
        duty = STOCK_MAX
    with open(fan_dir() + "/pwm1", "w") as f:
        f.write(str(duty))


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)
    for name, fn in (("status", cmd_status), ("check", cmd_check), ("run", cmd_run), ("stop", cmd_stop)):
        s = sub.add_parser(name)
        s.set_defaults(func=fn)
        if name == "check":
            s.add_argument("percent", type=float, help="share of Valve's stock top speed, 1-100")
        elif name == "run":
            s.add_argument("percent", type=float, nargs="?", help="used when the cap file is missing")
    args = p.parse_args()
    if getattr(args, "percent", None) is not None and not 0 < args.percent <= 100:
        p.error("percent must be in 1-100")
    args.func(args)


if __name__ == "__main__":
    main()
